"""Add loyalty config to Cafe and Bill fields to VerificationRequest

Revision ID: 360e6cb8790a
Revises: 948caf588983
Create Date: 2025-12-25 22:39:58.138428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '360e6cb8790a'
down_revision: Union[str, Sequence[str], None] = '948caf588983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafe', sa.Column('loyalty_config', sa.JSON(), nullable=True))
    op.alter_column('loyaltyaccount', 'points_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction', 'amount',
               existing_type=sa.INTEGER(),
               comment='In smallest currency unit (e.g. cents)',
               existing_nullable=False)
    op.alter_column('transaction', 'points_earned',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('verificationrequest', sa.Column('bill_id', sa.String(), nullable=True))
    op.add_column('verificationrequest', sa.Column('bill_amount', sa.Float(), nullable=True))
    op.add_column('verificationrequest', sa.Column('staff_id', sa.String(), nullable=True, comment='ID/Name of staff member'))
    op.add_column('verificationrequest', sa.Column('verbal_consent', sa.Boolean(), nullable=False))
    op.add_column('verificationrequest', sa.Column('customer_name_input', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verificationrequest', 'customer_name_input')
    op.drop_column('verificationrequest', 'verbal_consent')
    op.drop_column('verificationrequest', 'staff_id')
    op.drop_column('verificationrequest', 'bill_amount')
    op.drop_column('verificationrequest', 'bill_id')
    op.alter_column('transaction', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction', 'points_earned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction', 'amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='In smallest currency unit (e.g. cents)',
               existing_nullable=False)
    op.alter_column('loyaltyaccount', 'points_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('cafe', 'loyalty_config')
    # ### end Alembic commands ###
