"""create audit_logs table

Revision ID: 7be9e8aea099
Revises: df7a915a21ba
Create Date: 2025-12-28 22:20:34.207567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be9e8aea099'
down_revision: Union[str, Sequence[str], None] = 'df7a915a21ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_type', sa.Enum('STAFF', 'CUSTOMER', 'OWNER', 'PLATFORM_ADMIN', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('target_resource', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
