"""Add Chain model

Revision ID: 948caf588983
Revises: 80aec27fb816
Create Date: 2025-12-25 22:26:34.380502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948caf588983'
down_revision: Union[str, Sequence[str], None] = '80aec27fb816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_id'), 'chain', ['id'], unique=False)
    op.create_index(op.f('ix_chain_name'), 'chain', ['name'], unique=False)
    op.add_column('cafe', sa.Column('chain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cafe', 'chain', ['chain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cafe', type_='foreignkey')
    op.drop_column('cafe', 'chain_id')
    op.drop_index(op.f('ix_chain_name'), table_name='chain')
    op.drop_index(op.f('ix_chain_id'), table_name='chain')
    op.drop_table('chain')
    # ### end Alembic commands ###
