"""Add guest_count to Visit and CouponType to Coupon

Revision ID: df7a915a21ba
Revises: 360e6cb8790a
Create Date: 2025-12-25 23:14:35.622252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df7a915a21ba'
down_revision: Union[str, Sequence[str], None] = '360e6cb8790a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum type manually for PostgreSQL
    coupon_type = sa.Enum('REVIEW_REWARD', 'LOYALTY_REDEMPTION', name='coupontype')
    coupon_type.create(op.get_bind())
    
    op.add_column('coupon', sa.Column('type', sa.Enum('REVIEW_REWARD', 'LOYALTY_REDEMPTION', name='coupontype'), nullable=False))
    op.add_column('coupon', sa.Column('points_cost', sa.Integer(), nullable=True))
    op.add_column('verificationrequest', sa.Column('guest_count', sa.Integer(), nullable=False, comment='Number of additional guests for referral bonus'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verificationrequest', 'guest_count')
    op.drop_column('coupon', 'points_cost')
    op.drop_column('coupon', 'type')
    
    # Drop Enum type
    coupon_type = sa.Enum('REVIEW_REWARD', 'LOYALTY_REDEMPTION', name='coupontype')
    coupon_type.drop(op.get_bind())
    # ### end Alembic commands ###
